name: gdar
description: gapless playback of select grateful dead shows from archive.org
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  scrollable_positioned_list: ^0.3.8
  sliding_up_panel: ^2.0.0+1
  marquee: ^2.2.3

  # For Audio Playback
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.11

  # For State Management (Theme)
  provider: ^6.1.1

  # For saving the theme choice
  shared_preferences: ^2.2.2

  # For Date Formatting
  intl: ^0.20.2

  # For better logging
  logger: ^2.0.2

  # Material 3 Features
  dynamic_color: ^1.6.9
  animations: ^2.0.8
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0
  http: ^1.2.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.1
  build_runner: ^2.10.3

flutter:
  uses-material-design: true

  assets:
    - assets/data/shows.json
